version: 1
services:
  - type: web
    name: my-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      DATABASE_URL: postgresql://user:1lkA38wVKxnzLqibgIJXXwBhZH1ny3OY@dpg-crvadc1u0jms73anq6u0-a/task_master_1cen
    plan: free

  - type: static
    name: my-frontend
    env: static
    buildCommand: cd view && npm install && npm run build
    publishDir: frontend/build
    plan: free