version: 1
services:
  - type: web
    name: my-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      DATABASE_URL: postgresql://user:TTbNBgwE5mhAybK0Y9IUD4gyoEJK2aMx@dpg-cubn4mggph6c73a7u2f0-a/task_master_1ykq
    plan: free

  - type: static
    name: my-frontend
    env: static
    buildCommand: cd view && npm install && npm run build
    publishDir: frontend/build
    plan: free